name: GalaxyCoreKnockFFA
version: '${project.version}'
main: net.galaxycore.knockffa.KnockFFA
api-version: 1.16
depend: [ GalaxyCoreCore, LuckPerms ]
authors: [ Flo-Mit-H ]
website: https://galaxycore.net

commands:
    kffadb:
        permission: knockffa.command.kffadb
        description: The Debug Command
        usage: /kffadb [suicide|on|off|statreset]
